name: wrestling_news
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  go_router: 14.3.0
  flutter_native_splash: 2.4.2
  flutter_launcher_icons: 0.14.1
  cloud_firestore: 5.4.4
  http: 1.2.2
  freezed: 2.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#1a1c20"
  image: assets/fractured_wrestling_news.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fractured_wrestling_news.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fractured_wrestling_news.png

